CREATE TABLE IF NOT EXISTS `系统操作日志` (
  `序号` INT PRIMARY KEY AUTO_INCREMENT,
  `操作人` VARCHAR(50),
  `操作内容` VARCHAR(255),
  `操作时间` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `IP地址` VARCHAR(50)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;